### ISSUE TITLE
web-oh-my-grafana

### ISSUE THREAD

**Issue by jack-She1l** [sixstars/starctf2022#2]
web-oh-my-grafana能写个部署说明吗，没有dockerfile，安装不成功啊

**Comment by po1ng** [comment]
Dockerfile:
build:
      context: grafana-8.2.6/grafana-8.2.6/
      dockerfile: Dockerfile

或者参考这个issue https://github.com/sixstars/starctf2022/issues/1

**Comment by jack-She1l** [comment]
> Dockerfile: build: context: grafana-8.2.6/grafana-8.2.6/ dockerfile: Dockerfile
> 
> 或者参考这个issue #1

好的
